"""
Trust-first analytics pipeline.

Executes in 8 steps:
  1. Question Parser   — NL → structured intent (stub or LLM)
  2. Semantic Mapper   — intent → model concepts via SemanticResolver
  3. Time Resolver     — "last month" → ISO date range
  4. SQL Generator     — template-based SQL (never LLM) for full trustworthiness
  5. SQL Validator     — dangerous-keyword check + DuckDB EXPLAIN
  6. Execution Engine  — run against DuckDB
  7. Answer Formatter  — LLM summary or stub template
  8. Provenance Builder— assemble the full trust trace

The LLM is used only in steps 1 and 7. SQL is always generated by code.
"""

from __future__ import annotations

import re
import sys
import time
from dataclasses import asdict
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from packages.semantic_model.resolver import SemanticResolver  # noqa: E402

from .engine import QueryEngine  # noqa: E402
from .pipeline_types import (  # noqa: E402
    MappingResult,
    ParsedIntent,
    PipelineResult,
    TermMapping,
    TimeRange,
)

# ── Dangerous SQL patterns (deny-list) ────────────────────────────────────────

_DANGEROUS = re.compile(
    r"\b(DROP|DELETE|INSERT|UPDATE|ALTER|TRUNCATE|CREATE|REPLACE|ATTACH|DETACH"
    r"|PRAGMA|COPY|EXPORT|IMPORT|LOAD|INSTALL)\b",
    re.IGNORECASE,
)


# ── Main entry point ──────────────────────────────────────────────────────────


async def execute_pipeline(
    question: str,
    view_name: str,
    model_definition: dict,
    engine: QueryEngine,
    llm,  # LLMAdapter instance (duck-typed)
    settings,  # Settings instance
) -> PipelineResult:
    """Run the full analytics pipeline and return a trust-annotated result."""

    provenance_steps: list[dict] = []
    resolver = SemanticResolver(model_definition)

    # ── Step 1: Parse question ────────────────────────────────────────────────
    intent = await _parse_question(question, model_definition, llm, settings)
    provenance_steps.append({"step": "question_parser", "output": asdict(intent)})

    # ── Step 2: Map intent → semantic concepts ────────────────────────────────
    mapping = _map_intent(intent, resolver, model_definition)
    provenance_steps.append(
        {
            "step": "semantic_mapper",
            "output": {
                "resolved_metrics": [asdict(m) for m in mapping.resolved_metrics],
                "resolved_dimensions": [asdict(d) for d in mapping.resolved_dimensions],
                "unmapped": mapping.unmapped,
                "needs_clarification": mapping.needs_clarification,
            },
        }
    )

    # ── Clarification check ───────────────────────────────────────────────────
    if mapping.needs_clarification and not mapping.resolved_metrics:
        return PipelineResult.clarification(
            question=question,
            clarifying_question=mapping.clarifying_question or "Could you rephrase?",
            provenance={"steps": provenance_steps},
        )

    # ── Step 3: Resolve time expression ──────────────────────────────────────
    time_range = _resolve_time(intent.time_expression)
    if time_range:
        provenance_steps.append({"step": "time_resolver", "output": asdict(time_range)})

    # ── Step 4: Generate SQL ──────────────────────────────────────────────────
    sql, sql_assumptions = _generate_sql(
        view_name=view_name,
        resolved_metrics=mapping.resolved_metrics,
        resolved_dimensions=mapping.resolved_dimensions,
        model=model_definition,
        time_range=time_range,
        limit=intent.limit,
        sort_direction=intent.sort_direction,
        resolver=resolver,
    )
    provenance_steps.append({"step": "sql_generator", "output": {"sql": sql}})

    # ── Step 5: Validate SQL ──────────────────────────────────────────────────
    validation_error = _validate_sql_static(sql)
    if validation_error:
        return PipelineResult.error(
            question=question,
            error=f"SQL validation failed: {validation_error}",
            sql=sql,
            provenance={"steps": provenance_steps},
        )

    try:
        await engine.run(f"EXPLAIN {sql}")
    except Exception as exc:
        return PipelineResult.error(
            question=question,
            error=f"Generated SQL has a syntax error: {exc}",
            sql=sql,
            provenance={"steps": provenance_steps},
        )

    # ── Step 6: Execute ───────────────────────────────────────────────────────
    exec_start = time.monotonic()
    try:
        columns, rows = await engine.run(sql)
    except Exception as exc:
        return PipelineResult.error(
            question=question,
            error=f"Query execution failed: {exc}",
            sql=sql,
            provenance={"steps": provenance_steps},
        )
    execution_ms = int((time.monotonic() - exec_start) * 1000)
    provenance_steps.append(
        {
            "step": "execution_engine",
            "output": {
                "columns": columns,
                "row_count": len(rows),
                "execution_ms": execution_ms,
            },
        }
    )

    # ── Step 7: Format answer ─────────────────────────────────────────────────
    answer = await _format_answer(
        question=question,
        sql=sql,
        columns=columns,
        rows=rows,
        llm=llm,
        settings=settings,
    )

    # ── Step 8: Assemble provenance & trust metadata ──────────────────────────
    assumptions = mapping.assumptions + sql_assumptions
    confidence, confidence_note = _compute_confidence(mapping)
    chart_type = _suggest_chart(
        intent.question_type,
        mapping.resolved_metrics,
        mapping.resolved_dimensions,
        model_definition,
        len(rows),
    )
    semantic_mappings = [
        {
            "phrase": m.phrase,
            "resolved_to": m.resolved_to,
            "resolved_name": m.resolved_name,
            "type": m.resolved_type,
            "via": m.via,
        }
        for m in (mapping.resolved_metrics + mapping.resolved_dimensions)
    ]

    return PipelineResult(
        question=question,
        answer=answer,
        sql=sql,
        columns=columns,
        rows=rows[:1000],  # cap response size
        row_count=len(rows),
        chart_type=chart_type,
        semantic_mappings=semantic_mappings,
        assumptions=assumptions,
        caveats=model_definition.get("caveats", []),
        confidence=confidence,
        confidence_note=confidence_note,
        clarifying_question=None,
        provenance={
            "steps": provenance_steps,
            "model_name": model_definition.get("name"),
            "view_name": view_name,
        },
        execution_ms=execution_ms,
        error=None,
    )


# ── Step 1: Question Parser ────────────────────────────────────────────────────


async def _parse_question(
    question: str,
    model_def: dict,
    llm,
    settings,
) -> ParsedIntent:
    """Parse a NL question into structured intent.

    Uses the stub parser when no real API key is configured, or as a
    fallback if the LLM call fails.
    """
    if llm.is_stub:
        return _parse_stub(question, model_def)
    try:
        return await _parse_with_llm(question, model_def, llm)
    except Exception:
        return _parse_stub(question, model_def)


async def _parse_with_llm(question: str, model_def: dict, llm) -> ParsedIntent:
    """Call the LLM to extract structured intent as JSON."""
    model_context = _model_summary(model_def)
    messages = [
        {
            "role": "system",
            "content": (
                "You are an analytics query parser. Given a natural-language question "
                "and a semantic model, extract the structured intent.\n"
                "Return ONLY a valid JSON object — no markdown, no explanation.\n"
                "Schema:\n"
                "{\n"
                '  "question_type": "metric_lookup"|"breakdown"|"trend"|"comparison"|"ranking",\n'
                '  "candidate_terms": ["term1", ...],\n'
                '  "time_expression": "last month"|"last 7 days"|"2024"|null,\n'
                '  "explicit_group_by": ["dimension_name", ...],\n'
                '  "limit": null|integer,\n'
                '  "sort_direction": "desc"|"asc"\n'
                "}\n\n"
                "Rules:\n"
                "- candidate_terms: business terms that may map to metrics or dimensions\n"
                "- time_expression: verbatim time phrase if present, else null\n"
                "- explicit_group_by: dimensions the user asks to group by\n"
                "- ranking: question has 'top N' or 'bottom N'\n"
                "- trend: question mentions 'over time', 'monthly', 'daily', 'trend'\n"
            ),
        },
        {
            "role": "user",
            "content": (f"Question: {question}\n\n" f"Semantic model:\n{model_context}"),
        },
    ]
    data = await llm.complete_json(messages)
    return ParsedIntent(
        raw_question=question,
        question_type=data.get("question_type", "metric_lookup"),
        candidate_terms=data.get("candidate_terms", []),
        time_expression=data.get("time_expression"),
        explicit_group_by=data.get("explicit_group_by", []),
        limit=data.get("limit"),
        sort_direction=data.get("sort_direction", "desc"),
    )


def _parse_stub(question: str, model_def: dict) -> ParsedIntent:
    """Rule-based parser for offline/test mode — no LLM required."""
    q = question.lower()

    # Question type
    if re.search(r"\btop\s+\d+\b", q):
        qtype = "ranking"
    elif any(
        t in q
        for t in (
            "trend",
            "over time",
            "monthly",
            "weekly",
            "daily",
            "by month",
            "by week",
            "by day",
        )
    ):
        qtype = "trend"
    elif any(t in q for t in ("compare", " vs ", "versus")):
        qtype = "comparison"
    elif any(
        re.search(rf"\b(by|per|across|breakdown by)\s+{re.escape(d['name'].lower())}", q)
        or any(
            re.search(rf"\b(by|per|across|breakdown by)\s+{re.escape(a.lower())}", q)
            for a in d.get("aliases", [])
        )
        for d in model_def.get("dimensions", [])
    ):
        qtype = "breakdown"
    else:
        qtype = "metric_lookup"

    # Time expression
    time_patterns = [
        r"last \d+ days?",
        r"last week",
        r"last month",
        r"last quarter",
        r"last year",
        r"this week",
        r"this month",
        r"this quarter",
        r"this year",
        r"yesterday",
        r"today",
        r"q[1-4]\s+\d{4}",
        r"\b\d{4}\b",
    ]
    time_expression: str | None = None
    for pat in time_patterns:
        m = re.search(pat, q)
        if m:
            time_expression = m.group(0)
            break

    # Top N limit
    limit: int | None = None
    m = re.search(r"\btop\s+(\d+)\b", q)
    if m:
        limit = int(m.group(1))

    # Candidate terms — scan metric names, aliases, dimension names, aliases, synonyms
    candidate_terms: list[str] = []
    seen: set[str] = set()

    def _add(term: str) -> None:
        if term not in seen:
            seen.add(term)
            candidate_terms.append(term)

    for metric in model_def.get("metrics", []):
        if metric["name"].lower() in q:
            _add(metric["name"])
        for alias in metric.get("aliases", []):
            if alias.lower() in q:
                _add(alias)

    for dim in model_def.get("dimensions", []):
        if dim["name"].lower() in q:
            _add(dim["name"])
        for alias in dim.get("aliases", []):
            if alias.lower() in q:
                _add(alias)

    for syn in model_def.get("synonyms", []):
        if syn["phrase"].lower() in q:
            _add(syn["phrase"])

    # Explicit group-by detection ("by X", "per X", etc.)
    explicit_group_by: list[str] = []
    for dim in model_def.get("dimensions", []):
        all_names = [dim["name"].lower()] + [a.lower() for a in dim.get("aliases", [])]
        for n in all_names:
            pattern = rf"\b(by|per|across|breakdown by)\s+{re.escape(n)}\b"
            if re.search(pattern, q):
                if dim["name"] not in explicit_group_by:
                    explicit_group_by.append(dim["name"])
                    _add(dim["name"])
                break

    sort_direction = "asc" if "bottom" in q else "desc"

    return ParsedIntent(
        raw_question=question,
        question_type=qtype,
        candidate_terms=candidate_terms,
        time_expression=time_expression,
        explicit_group_by=explicit_group_by,
        limit=limit,
        sort_direction=sort_direction,
    )


def _model_summary(model_def: dict) -> str:
    """Compact model description for LLM prompts."""
    lines = [f"Name: {model_def.get('name')}"]
    metrics = model_def.get("metrics", [])
    if metrics:
        lines.append(
            "Metrics: "
            + ", ".join(
                f"{m['name']}"
                + (f" (aliases: {', '.join(m['aliases'])})" if m.get("aliases") else "")
                for m in metrics
            )
        )
    dims = model_def.get("dimensions", [])
    if dims:
        lines.append(
            "Dimensions: "
            + ", ".join(
                f"{d['name']}"
                + (f" (aliases: {', '.join(d['aliases'])})" if d.get("aliases") else "")
                for d in dims
            )
        )
    return "\n".join(lines)


# ── Step 2: Semantic Mapper ────────────────────────────────────────────────────


def _map_intent(
    intent: ParsedIntent,
    resolver: SemanticResolver,
    model_def: dict,
) -> MappingResult:
    """Map candidate terms to concrete model metrics and dimensions."""
    resolver.resolve(intent.raw_question)
    resolved_metrics: list[TermMapping] = []
    resolved_dimensions: list[TermMapping] = []
    unmapped: list[str] = []
    assumptions: list[str] = []
    seen_metric_names: set[str] = set()
    seen_dim_names: set[str] = set()

    for term in intent.candidate_terms:
        term_lower = term.lower()

        # Try metric match
        metric = _find_metric(term_lower, model_def)
        if metric and metric["name"] not in seen_metric_names:
            seen_metric_names.add(metric["name"])
            via = "exact" if term_lower == metric["name"].lower() else "alias"
            resolved_metrics.append(
                TermMapping(
                    phrase=term,
                    resolved_name=metric["name"],
                    resolved_type="metric",
                    resolved_to=f"metric:{metric['name']}",
                    via=via,
                    confidence=1.0 if via == "exact" else 0.8,
                )
            )
            continue

        # Try dimension match
        dim = _find_dimension(term_lower, model_def)
        if dim and dim["name"] not in seen_dim_names:
            seen_dim_names.add(dim["name"])
            via = "exact" if term_lower == dim["name"].lower() else "alias"
            resolved_dimensions.append(
                TermMapping(
                    phrase=term,
                    resolved_name=dim["name"],
                    resolved_type="dimension",
                    resolved_to=f"dimension:{dim['name']}",
                    via=via,
                    confidence=1.0 if via == "exact" else 0.8,
                )
            )
            continue

        unmapped.append(term)

    # Add explicit group-by dimensions not yet resolved
    for dim_name in intent.explicit_group_by:
        if dim_name not in seen_dim_names:
            dim = next(
                (d for d in model_def.get("dimensions", []) if d["name"] == dim_name),
                None,
            )
            if dim:
                seen_dim_names.add(dim_name)
                resolved_dimensions.append(
                    TermMapping(
                        phrase=dim_name,
                        resolved_name=dim["name"],
                        resolved_type="dimension",
                        resolved_to=f"dimension:{dim['name']}",
                        via="exact",
                        confidence=1.0,
                    )
                )

    # If no metrics resolved but model has exactly one metric, default to it
    if not resolved_metrics and len(model_def.get("metrics", [])) == 1:
        m = model_def["metrics"][0]
        resolved_metrics.append(
            TermMapping(
                phrase=m["name"],
                resolved_name=m["name"],
                resolved_type="metric",
                resolved_to=f"metric:{m['name']}",
                via="default",
                confidence=0.5,
            )
        )
        assumptions.append(
            f"No specific metric mentioned; defaulted to '{m['name']}' "
            f"(the only metric in this model)."
        )

    # Determine if clarification is needed
    needs_clarification = not resolved_metrics
    clarifying_question: str | None = None
    if needs_clarification:
        metric_names = ", ".join(m["name"] for m in model_def.get("metrics", []))
        clarifying_question = (
            f"I couldn't identify which metric you're asking about. "
            f"Available metrics: {metric_names}. Could you rephrase?"
        )

    overall = (
        min((m.confidence for m in resolved_metrics + resolved_dimensions), default=0.5)
        if not needs_clarification
        else 0.1
    )

    return MappingResult(
        resolved_metrics=resolved_metrics,
        resolved_dimensions=resolved_dimensions,
        unmapped=unmapped,
        assumptions=assumptions,
        overall_confidence=overall,
        needs_clarification=needs_clarification,
        clarifying_question=clarifying_question,
    )


def _find_metric(term_lower: str, model_def: dict) -> dict | None:
    for m in model_def.get("metrics", []):
        if m["name"].lower() == term_lower:
            return m
        if any(a.lower() == term_lower for a in m.get("aliases", [])):
            return m
    # Check synonyms
    for syn in model_def.get("synonyms", []):
        if syn["phrase"].lower() == term_lower and syn["maps_to"].startswith("metric:"):
            target = syn["maps_to"][7:]
            return next((m for m in model_def.get("metrics", []) if m["name"] == target), None)
    return None


def _find_dimension(term_lower: str, model_def: dict) -> dict | None:
    for d in model_def.get("dimensions", []):
        if d["name"].lower() == term_lower:
            return d
        if any(a.lower() == term_lower for a in d.get("aliases", [])):
            return d
    # Check synonyms
    for syn in model_def.get("synonyms", []):
        if syn["phrase"].lower() == term_lower and syn["maps_to"].startswith("dimension:"):
            target = syn["maps_to"][10:]
            return next((d for d in model_def.get("dimensions", []) if d["name"] == target), None)
    return None


# ── Step 3: Time Resolver ──────────────────────────────────────────────────────


def _resolve_time(expr: str | None) -> TimeRange | None:
    """Resolve a natural language time expression to an ISO date range."""
    if not expr:
        return None
    return _parse_time_expression(expr.lower(), date.today())


def _parse_time_expression(expr: str, today: date) -> TimeRange | None:  # noqa: C901
    """Map a lower-cased time phrase to a concrete [start, end) date range."""

    if expr == "today":
        return TimeRange(
            start=str(today),
            end=str(today + timedelta(days=1)),
            label="today",
            assumption=f"Interpreted 'today' as {today}.",
        )

    if expr == "yesterday":
        d = today - timedelta(days=1)
        return TimeRange(
            start=str(d),
            end=str(today),
            label="yesterday",
            assumption=f"Interpreted 'yesterday' as {d}.",
        )

    m = re.match(r"last (\d+) days?", expr)
    if m:
        n = int(m.group(1))
        start = today - timedelta(days=n)
        return TimeRange(
            start=str(start),
            end=str(today + timedelta(days=1)),
            label=f"last {n} days",
            assumption=f"Interpreted 'last {n} days' as {start} to {today}.",
        )

    if "last week" in expr or "this week" in expr:
        prefix = "last" if "last" in expr else "this"
        offset = 7 if prefix == "last" else 0
        days_since_mon = today.weekday()
        monday = today - timedelta(days=days_since_mon + offset)
        sunday = monday + timedelta(days=6)
        return TimeRange(
            start=str(monday),
            end=str(sunday + timedelta(days=1)),
            label=f"{prefix} week",
            assumption=f"Interpreted '{prefix} week' as {monday} to {sunday}.",
        )

    if "last month" in expr or "this month" in expr:
        if "last" in expr:
            first_of_current = today.replace(day=1)
            last_of_prev = first_of_current - timedelta(days=1)
            start = last_of_prev.replace(day=1)
            end = first_of_current
            label_end = last_of_prev
        else:
            start = today.replace(day=1)
            end = today + timedelta(days=1)
            label_end = today
        prefix = "last" if "last" in expr else "this"
        return TimeRange(
            start=str(start),
            end=str(end),
            label=f"{prefix} month",
            assumption=f"Interpreted '{prefix} month' as {start} to {label_end}.",
        )

    if "last quarter" in expr or "this quarter" in expr:
        current_q = (today.month - 1) // 3  # 0-indexed
        if "last" in expr:
            if current_q == 0:
                q, year = 3, today.year - 1
            else:
                q, year = current_q - 1, today.year
        else:
            q, year = current_q, today.year
        start_month = q * 3 + 1
        end_month = start_month + 3
        start_d = date(year, start_month, 1)
        end_d = date(year, end_month, 1) if end_month <= 12 else date(year + 1, 1, 1)
        q_label = f"Q{q + 1} {year}"
        prefix = "last" if "last" in expr else "this"
        return TimeRange(
            start=str(start_d),
            end=str(end_d),
            label=q_label,
            assumption=f"Interpreted '{prefix} quarter' as {q_label} ({start_d} to {end_d - timedelta(days=1)}).",
        )

    if "last year" in expr or "this year" in expr:
        year = today.year - (1 if "last" in expr else 0)
        end = today + timedelta(days=1) if "this" in expr else date(year + 1, 1, 1)
        prefix = "last" if "last" in expr else "this"
        return TimeRange(
            start=f"{year}-01-01",
            end=str(end),
            label=str(year),
            assumption=f"Interpreted '{prefix} year' as calendar year {year}.",
        )

    # Q1 2024, Q2 2025, etc.
    m = re.match(r"q([1-4])\s*(\d{4})", expr)
    if m:
        q, year = int(m.group(1)), int(m.group(2))
        start_month = (q - 1) * 3 + 1
        end_month = start_month + 3
        start_d = date(year, start_month, 1)
        end_d = date(year, end_month, 1) if end_month <= 12 else date(year + 1, 1, 1)
        label = f"Q{q} {year}"
        return TimeRange(
            start=str(start_d),
            end=str(end_d),
            label=label,
            assumption=f"Interpreted 'Q{q} {year}' as {start_d} to {end_d - timedelta(days=1)}.",
        )

    # Plain year: 2024
    m = re.match(r"(\d{4})$", expr.strip())
    if m:
        year = int(m.group(1))
        return TimeRange(
            start=f"{year}-01-01",
            end=f"{year + 1}-01-01",
            label=str(year),
            assumption=f"Interpreted '{year}' as the full calendar year {year}.",
        )

    return None


# ── Step 4: SQL Generator ──────────────────────────────────────────────────────


def _generate_sql(
    view_name: str,
    resolved_metrics: list[TermMapping],
    resolved_dimensions: list[TermMapping],
    model: dict,
    time_range: TimeRange | None,
    limit: int | None,
    sort_direction: str,
    resolver: SemanticResolver,
) -> tuple[str, list[str]]:
    """Generate a DuckDB SELECT statement from resolved model concepts.

    Returns (sql, list_of_assumption_strings).
    """
    assumptions: list[str] = []

    # ── SELECT ────────────────────────────────────────────────────────────────
    select_parts: list[str] = []

    for dim_m in resolved_dimensions:
        dim_def = next(
            (d for d in model.get("dimensions", []) if d["name"] == dim_m.resolved_name),
            None,
        )
        col = dim_def["column"] if dim_def else dim_m.resolved_name
        select_parts.append(f'"{col}" AS {dim_m.resolved_name}')

    for met_m in resolved_metrics:
        sql_expr = resolver.metric_sql(met_m.resolved_name)
        if sql_expr is None:
            # Fallback: use raw expression from model
            met_def = next(
                (m for m in model.get("metrics", []) if m["name"] == met_m.resolved_name),
                None,
            )
            sql_expr = met_def["expression"] if met_def else met_m.resolved_name
        select_parts.append(f"{sql_expr} AS {met_m.resolved_name}")

    select_clause = ",\n  ".join(select_parts)

    # ── WHERE ─────────────────────────────────────────────────────────────────
    where_parts: list[str] = []
    time_col = model.get("time_column")

    if time_range and time_col:
        where_parts.append(f"\"{time_col}\" >= '{time_range.start}'")
        where_parts.append(f"\"{time_col}\" < '{time_range.end}'")
        assumptions.append(time_range.assumption)
    elif time_range and not time_col:
        assumptions.append(
            "A time range was mentioned but this model has no time_column defined — "
            "the time filter was not applied."
        )

    # Business rules — apply rules that are either global or match selected metrics/dimensions
    selected_metric_refs = {f"metric:{m.resolved_name}" for m in resolved_metrics}
    selected_dim_refs = {f"dimension:{d.resolved_name}" for d in resolved_dimensions}
    selected_refs = selected_metric_refs | selected_dim_refs

    for rule in model.get("business_rules", []):
        applies_to = rule.get("applies_to", [])
        if not applies_to or any(ref in selected_refs for ref in applies_to):
            where_parts.append(f"({rule['filter']})")

    # ── GROUP BY ──────────────────────────────────────────────────────────────
    group_by_parts: list[str] = []
    for dim_m in resolved_dimensions:
        dim_def = next(
            (d for d in model.get("dimensions", []) if d["name"] == dim_m.resolved_name),
            None,
        )
        col = dim_def["column"] if dim_def else dim_m.resolved_name
        group_by_parts.append(f'"{col}"')

    # ── ORDER BY ──────────────────────────────────────────────────────────────
    order_by: str | None = None
    if resolved_metrics:
        order_by = f"{resolved_metrics[0].resolved_name} {sort_direction.upper()}"
    elif resolved_dimensions:
        dim_def = next(
            (
                d
                for d in model.get("dimensions", [])
                if d["name"] == resolved_dimensions[0].resolved_name
            ),
            None,
        )
        col = dim_def["column"] if dim_def else resolved_dimensions[0].resolved_name
        order_by = f'"{col}" ASC'

    # ── Build SQL ─────────────────────────────────────────────────────────────
    sql = f'SELECT\n  {select_clause}\nFROM "{view_name}"'

    if where_parts:
        sql += "\nWHERE " + "\n  AND ".join(where_parts)

    if group_by_parts:
        sql += "\nGROUP BY " + ", ".join(group_by_parts)

    if order_by:
        sql += f"\nORDER BY {order_by}"

    if limit:
        sql += f"\nLIMIT {limit}"

    # Assumption: note the aggregation choice
    if resolved_metrics and not resolved_dimensions:
        assumptions.append(
            f"Aggregated the full dataset into a single {sorted_direction_label(sort_direction)} value."
        )

    return sql, assumptions


def sorted_direction_label(direction: str) -> str:
    return "total" if direction == "desc" else "ranked"


# ── Step 5: SQL Validator ──────────────────────────────────────────────────────


def _validate_sql_static(sql: str) -> str | None:
    """Return an error message if the SQL contains dangerous patterns, else None."""
    match = _DANGEROUS.search(sql)
    if match:
        return (
            f"SQL contains a disallowed keyword '{match.group()}'. "
            "Only SELECT statements are permitted."
        )
    return None


# ── Step 7: Answer Formatter ───────────────────────────────────────────────────


async def _format_answer(
    question: str,
    sql: str,
    columns: list[str],
    rows: list[list],
    llm,
    settings,
) -> str:
    """Generate a concise human-readable answer.

    Uses the LLM when available; falls back to a template.
    """
    if llm.is_stub or not rows:
        return _format_stub(question, columns, rows)
    try:
        return await _format_with_llm(question, sql, columns, rows, llm)
    except Exception:
        return _format_stub(question, columns, rows)


async def _format_with_llm(
    question: str,
    sql: str,
    columns: list[str],
    rows: list[list],
    llm,
) -> str:
    # Send at most 10 rows to the LLM
    preview = rows[:10]
    rows_text = "\n".join("  " + ", ".join(str(v) for v in row) for row in preview)
    more = f"\n  ... and {len(rows) - 10} more rows" if len(rows) > 10 else ""
    messages = [
        {
            "role": "system",
            "content": (
                "You are a data analyst presenting results to a business user. "
                "Write a concise 1-3 sentence answer based on the data. "
                "Include specific numbers and values. "
                "Do NOT say 'According to the query' or explain the SQL. "
                "For currencies use $ and commas. For percentages include %. "
                "If there are no rows, say no data was found."
            ),
        },
        {
            "role": "user",
            "content": (
                f"Question: {question}\n\n"
                f"Columns: {', '.join(columns)}\n"
                f"Results:\n{rows_text}{more}\n"
                f"Total rows: {len(rows)}"
            ),
        },
    ]
    return await llm.complete(messages)


def _format_stub(question: str, columns: list[str], rows: list[list]) -> str:
    if not rows:
        return "No data matched your query. Try adjusting the filters or time range."
    if len(columns) == 1 and len(rows) == 1:
        val = rows[0][0]
        return f"The result is {_fmt_value(val)}."
    return (
        f"The query returned {len(rows)} row{'s' if len(rows) != 1 else ''} "
        f"with column{'s' if len(columns) != 1 else ''}: {', '.join(columns)}."
    )


def _fmt_value(v) -> str:
    if isinstance(v, float):
        return f"{v:,.2f}"
    if isinstance(v, int):
        return f"{v:,}"
    return str(v)


# ── Confidence Scoring ─────────────────────────────────────────────────────────


def _compute_confidence(mapping: MappingResult) -> tuple[str, str]:
    """Return (confidence_level, confidence_note)."""
    if mapping.needs_clarification:
        return (
            "clarification_needed",
            "The question is ambiguous — no metrics could be identified.",
        )

    if not mapping.resolved_metrics:
        return (
            "low",
            "No metrics were resolved. Check that your semantic model defines the terms used.",
        )

    all_mappings = mapping.resolved_metrics + mapping.resolved_dimensions
    min_conf = min((m.confidence for m in all_mappings), default=0.5)
    has_default = any(m.via == "default" for m in all_mappings)
    has_alias = any(m.via in ("alias", "synonym") for m in all_mappings)
    has_unmapped = bool(mapping.unmapped)

    if min_conf >= 0.95 and not has_default and not has_alias and not has_unmapped:
        return (
            "high",
            "All terms mapped exactly to defined metrics and dimensions.",
        )

    notes: list[str] = []
    if has_default:
        notes.append("used a default metric (no metric was explicitly mentioned)")
    if has_alias:
        notes.append("some terms matched via aliases or synonyms")
    if has_unmapped:
        notes.append(f"ignored unrecognised terms: {', '.join(mapping.unmapped)}")

    if min_conf >= 0.5:
        return (
            "medium",
            "Answer is likely correct. " + "; ".join(notes) + ".",
        )
    return (
        "low",
        "Confidence is low — significant assumptions were made. " + "; ".join(notes) + ".",
    )


# ── Chart Type Suggestion ──────────────────────────────────────────────────────


def _suggest_chart(
    question_type: str,
    resolved_metrics: list[TermMapping],
    resolved_dimensions: list[TermMapping],
    model: dict,
    row_count: int,
) -> str:
    n_dims = len(resolved_dimensions)
    n_metrics = len(resolved_metrics)

    if n_dims == 0:
        return "metric"  # single KPI card

    if row_count > 25 or n_dims > 1:
        return "table"

    if n_dims == 1:
        dim_name = resolved_dimensions[0].resolved_name
        dim_def = next((d for d in model.get("dimensions", []) if d["name"] == dim_name), None)
        is_date = dim_def.get("is_date", False) if dim_def else False

        if is_date or question_type == "trend":
            return "line"
        if question_type == "ranking":
            return "bar"
        if n_metrics == 1:
            return "bar"
        return "grouped_bar"

    return "table"
