"""MetricAnchor API — entry point."""

from __future__ import annotations

import logging
import time
import uuid
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI, Request, Response
from fastapi.middleware.cors import CORSMiddleware
from logging_config import configure_logging

from config import get_settings
from db import get_session, init_db
from deps import get_query_engine
from routers import datasets, health, questions, semantic_models
from services.ingest import IngestService

configure_logging()
logger = logging.getLogger("metricanchor.api")


@asynccontextmanager
async def lifespan(app: FastAPI):
    settings = get_settings()
    logger.info(
        "MetricAnchor API starting",
        extra={
            "llm_provider": settings.llm_provider,
            "llm_model": settings.llm_model,
            "llm_live": bool(settings.llm_api_key and settings.llm_api_key != "test-key"),
            "data_dir": settings.data_dir,
        },
    )

    # Ensure data directories exist
    Path(settings.data_dir).mkdir(parents=True, exist_ok=True)
    (Path(settings.data_dir) / "uploads").mkdir(exist_ok=True)

    # Initialise SQLite tables
    await init_db()

    # Re-register all dataset views in DuckDB after restart
    engine = get_query_engine()
    async for db in get_session():
        svc = IngestService(db=db, engine=engine)
        await svc.restore_all_views()
        break

    logger.info("MetricAnchor API ready")
    yield
    logger.info("MetricAnchor API shutting down")


def create_app() -> FastAPI:
    settings = get_settings()

    app = FastAPI(
        title="MetricAnchor API",
        description=(
            "**Trust-first AI analytics copilot.**\n\n"
            "Every answer includes:\n"
            "- The exact SQL that was run\n"
            "- How each business term was mapped to a metric or dimension\n"
            "- Assumptions made during query generation\n"
            "- A confidence level (high / medium / low)\n"
            "- Full provenance trace through all pipeline steps\n\n"
            "**Pipeline steps:** question_parser → semantic_mapper → time_resolver → "
            "sql_generator → sql_validator → execution_engine → answer_formatter\n\n"
            "**LLM usage:** only steps 1 (parsing) and 7 (formatting). "
            "SQL is always generated by deterministic code — never by the LLM."
        ),
        version="0.3.0",
        docs_url="/api/docs",
        redoc_url="/api/redoc",
        openapi_url="/api/openapi.json",
        contact={"name": "MetricAnchor", "url": "https://github.com/metricanchor"},
        license_info={"name": "MIT"},
        lifespan=lifespan,
    )

    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_origins,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    @app.middleware("http")
    async def request_id_and_logging(request: Request, call_next) -> Response:
        request_id = request.headers.get("X-Request-ID") or str(uuid.uuid4())[:8]
        start = time.monotonic()
        response = await call_next(request)
        duration_ms = int((time.monotonic() - start) * 1000)
        response.headers["X-Request-ID"] = request_id
        logger.info(
            f"{request.method} {request.url.path} → {response.status_code}",
            extra={
                "request_id": request_id,
                "method": request.method,
                "path": request.url.path,
                "status": response.status_code,
                "duration_ms": duration_ms,
            },
        )
        return response

    app.include_router(health.router, prefix="/api")
    app.include_router(datasets.router, prefix="/api")
    app.include_router(semantic_models.router, prefix="/api")
    app.include_router(questions.router, prefix="/api")

    return app


app = create_app()
